# Works only if github.event.release.tag_name == package version
name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build package
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: dist/

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    name: Add package to release
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: builds
        path: dist/
    - name: Deploy package
      run: |
          cd ${{github.workspace}}/dist
          gh release upload ${{github.event.release.tag_name}} rsudp-${{github.event.release.tag_name}}-py3-none-any.whl
          gh release upload ${{github.event.release.tag_name}} rsudp-${{github.event.release.tag_name}}.tar.gz
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      shell: bash

  pypi:
    needs: [build]
    runs-on: ubuntu-latest
    name: Add package to PyPI
    environment:
      name: pypi
      url: https://pypi.org/p/rsudp
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: builds
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1