# Works only if github.event.release.tag_name == package version
name: Build Docs

on:
  push:
    branches:
      - master
      - develop
    paths:
      - docsrc/**

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Sphinx==8.1.3
          pip install docutils==0.20.1
          pip install sphinx_rtd_theme==3.0.2
          pip install "Jinja2<3.1"
      - name: Build
        run: |
          cd docsrc/
          make github
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: docsrc/_build/html